/**
 * 📍 Branchora Locator - Export Logic
 * 
 * AUTHOR: Vijaya Kumar L
 * SOURCE: github.com/risewithvj
 * (c) 2026 vjbuilds. All Rights Reserved.
 */

export function exportBranchesToJS(branches) {
    const content = `/**\n * Generated by Branchora Locator Management Suite\n * AUTHOR: Vijaya Kumar L\n * SOURCE: github.com/risewithvj\n */\nexport const branches = ${JSON.stringify(branches, null, 2)};`;
    const blob = new Blob([content], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'branches-data.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}