/**
 * 📍 Branchora Locator - Admin Suite
 * 
 * AUTHOR: Vijaya Kumar L
 * SOURCE: github.com/risewithvj
 * (c) 2026 vjbuilds. All Rights Reserved.
 */
import React, { useState } from 'react';
import { Branch } from '../../types';
import BranchForm from './BranchForm';

interface AdminPanelProps {
  branches: Branch[];
  onUpdateBranches: (branches: Branch[]) => void;
}

const AdminPanel: React.FC<AdminPanelProps> = ({ branches, onUpdateBranches }) => {
  const [isAdding, setIsAdding] = useState(false);
  const [editingBranch, setEditingBranch] = useState<Branch | null>(null);

  const handleExport = () => {
    const dataString = `/**\n * Generated by Branchora Locator Management Suite\n * AUTHOR: Vijaya Kumar L\n * SOURCE: github.com/risewithvj\n */\nexport const branches = ${JSON.stringify(branches, null, 2)};`;
    const blob = new Blob([dataString], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'branches-data.js';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDelete = (id: string) => {
    if (window.confirm('Are you sure you want to delete this branch?')) {
      onUpdateBranches(branches.filter(b => b.id !== id));
    }
  };

  const handleSave = (branchData: Partial<Branch>) => {
    if (editingBranch) {
      onUpdateBranches(branches.map(b => b.id === editingBranch.id ? { ...b, ...branchData } : b as Branch));
    } else {
      const newBranch: Branch = {
        ...branchData as Branch,
        id: Math.random().toString(36).substr(2, 9),
      };
      onUpdateBranches([...branches, newBranch]);
    }
    setIsAdding(false);
    setEditingBranch(null);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-12 flex flex-col min-h-[90vh]">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-10">
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Admin Dashboard</h1>
          <p className="text-slate-500 mt-1">Manage office locations for Branchora Locator</p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handleExport}
            className="flex items-center px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors shadow-sm text-sm font-semibold"
          >
            <i className="fas fa-file-export mr-2 text-indigo-500"></i> Export JS
          </button>
          <button
            onClick={() => {
              setEditingBranch(null);
              setIsAdding(true);
            }}
            className="flex items-center px-5 py-2.5 bg-indigo-600 text-white rounded-xl hover:bg-indigo-700 transition-colors shadow-md font-bold text-sm"
          >
            <i className="fas fa-plus mr-2"></i> Add Branch
          </button>
        </div>
      </div>

      {(isAdding || editingBranch) && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="p-8">
              <div className="flex justify-between items-center mb-6">
                <h2 className="text-2xl font-bold text-slate-900">
                  {editingBranch ? 'Edit Branch' : 'Add New Branch'}
                </h2>
                <button 
                  onClick={() => { setIsAdding(false); setEditingBranch(null); }}
                  className="text-slate-400 hover:text-slate-600"
                >
                  <i className="fas fa-times text-xl"></i>
                </button>
              </div>
              <BranchForm 
                initialData={editingBranch || undefined} 
                onSave={handleSave} 
                onCancel={() => { setIsAdding(false); setEditingBranch(null); }}
              />
            </div>
          </div>
        </div>
      )}

      <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden flex-grow">
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="bg-slate-50 border-b border-slate-200">
              <tr>
                <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Order</th>
                <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Branch Info</th>
                <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider">Contact Details</th>
                <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {branches.sort((a,b) => (a.order || 0) - (b.order || 0)).map(branch => (
                <tr key={branch.id} className="hover:bg-slate-50/50 transition-colors">
                  <td className="px-6 py-4 text-slate-400 font-mono text-sm">#{branch.order?.toString().padStart(2, '0') || '00'}</td>
                  <td className="px-6 py-4">
                    <div className="font-bold text-slate-900">{branch.name}</div>
                    <div className="text-xs text-slate-500 truncate max-w-xs">{branch.address}</div>
                  </td>
                  <td className="px-6 py-4 text-sm text-slate-600">
                    <div>{branch.phone}</div>
                    <div className="text-[10px] text-slate-400 font-mono">{branch.pincode}</div>
                  </td>
                  <td className="px-6 py-4 text-right space-x-2">
                    <button 
                      onClick={() => setEditingBranch(branch)}
                      className="p-2 text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
                      title="Edit"
                    >
                      <i className="fas fa-edit"></i>
                    </button>
                    <button 
                      onClick={() => handleDelete(branch.id)}
                      className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                      title="Delete"
                    >
                      <i className="fas fa-trash-alt"></i>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <footer className="py-12 text-center mt-auto">
        <p className="text-slate-400 text-[11px] md:text-xs tracking-tight">
          © 2026 Built by <span className="font-bold">vjbuilds</span>. All rights reserved. github.com/risewithvj
        </p>
      </footer>
    </div>
  );
};

export default AdminPanel;